/rhome/m/mucanbarli1/workspace/TP/T6/Z1/main.cpp: In function ‘int main()’:
/rhome/m/mucanbarli1/workspace/TP/T6/Z1/main.cpp:56:4: warning: exception of type ‘std::overflow_error’ will be caught
  } catch(std::overflow_error d) {
    ^~~~~
/rhome/m/mucanbarli1/workspace/TP/T6/Z1/main.cpp:53:4: warning:    by earlier handler for ‘std::runtime_error’
  } catch(std::runtime_error e) {
    ^~~~~
